synthetic-package: false
output-dir: lib/l10n/generated
arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: flutter_extension_localizations.dart
output-class: FlutterExtensionLocalizations