name: flutter_extensions
description: My flutter extensions.
version: 0.0.1
homepage:

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  # Enable generation of localized Strings from arb files.
  generate: true